from __future__ import annotations


CONFIG = {
    "project": {
        "root_dir": ".",
        "output_dir": "./output/model_analysis_20260429",
        "log_level": "INFO",
    },
    "output_files": {
        "risk_performance": "model_bin_risk_performance_pivot.xlsx",
        "feature_mean_profile": "model_bin_feature_mean_profile.xlsx",
        "user_profile": "model_bin_user_profile_pivot.xlsx",
    },
    "input_tables": {
        "base_sample": {"path": "./INPUT/main_analysis_model.csv"},
        "customer_profile": {"path": "./INPUT/business_analysis_variable_library.csv"},
        "comparison_score": {"path": "./INPUT/cross_model_score.csv"},
        "occupation_information": {"path": "./INPUT/occupation_information.csv"},
    },
    "feature_profile": {
        "variable_library_path": "./INPUT/model_variable_library.csv",
    },
    "keys": {
        "primary_key": "application_id",
        "user_key": "user_id",
        "datetime_key": "sample_datetime",
        "datetime_aliases": ["sample_datime"],
    },
    "analysis": {
        "base_table": "base_sample",
        "sample_month_field": "sample_month",
    },
    "score_binning": {
        # 所有模型分统一等频分箱；-1 单独成箱，不参与等频切分。
        "binning_mode": "equal_frequency",
        "scores": [
            {
                "name": "primary_model_score",
                "source_table": "base_sample",
                "score_field": "aus_new_worthiness_bid_3rdmodel_v1_0_20260429",
                "bin_field": "primary_model_score_bin",
                "bin_label_type": "int",
                "bin_count": 5,
                "bin_labels": [1, 2, 3, 4, 5],
                "special_values": [-1],
                "special_label_map": {-1: -1},
            },
            {
                "name": "comparison_model_score",
                "source_table": "comparison_score",
                "score_field": "aus_new_risk_bid_3rdmodel_v1_0_20251201",
                "bin_field": "comparison_model_score_bin",
                "bin_label_type": "int",
                "bin_count": 5,
                "bin_labels": [1, 2, 3, 4, 5],
                "special_values": [-1],
                "special_label_map": {-1: -1},
            },
        ],
    },
    "joins": {
        "customer_profile": {
            "source_table": "customer_profile",
            "join_key": "application_id",
            "fields": [
                "PTI",
                "principal",
                "estimate_principal_remaining_mob3",
                "dpd_days_mob3",
                "estimate_principal_remaining_mob1",
                "dpd_days_mob1",
                "gross_surplus",
                "net_surplus",
                "total_income",
                "requested_loan_amount",
                "total_amount",
                "age",
                "state",
                "suburb",
                "family_type",
                "dependents",
                "attributed_category",
                "duedate_1m_5",
                "duedate_3m_30",
                "application_status",
                "assessment_status",
                "status",
            ],
        },
        "comparison_score": {
            "source_table": "comparison_score",
            "join_key": "application_id",
            "fields": ["aus_new_risk_bid_3rdmodel_v1_0_20251201"],
        },
        "txn_industry_features": {
            "source_table": "occupation_information",
            "join_key": "application_id",
            "fields": [
                "bank_txn_industry_primary_industry",
                "bank_txn_industry_primary_industry_amt",
                "bank_txn_industry_pay_interval_median",
                "bank_txn_industry_pay_interval_std",
                "bank_txn_industry_primary_employer",
                "bank_txn_industry_primary_employer_ratio",
                "bank_txn_industry_employer_cnt",
            ],
        },
    },
    "amount_rules": {
        "deal_status_field": "status",
        "deal_status_values": ["Active_Account", "Closed", "Blocked"],
        "total_amount_field": "total_amount",
        "deal_total_amount_field": "deal_total_amount",
    },
    "risk_metrics": {
        "label_metrics": [
            {"field": "duedate_3m_30", "prefix": "duedate_3m_30", "bad_values": [1], "good_values": [0]},
            {"field": "duedate_1m_5", "prefix": "duedate_1m_5", "bad_values": [1], "good_values": [0]},
        ],
        "amount_overdue_metrics": [
            {
                "prefix": "duedate_3m_30_amount",
                "dpd_field": "dpd_days_mob3",
                "overdue_threshold": 30,
                "numerator_field": "estimate_principal_remaining_mob3",
                "denominator_field": "principal",
            },
            {
                "prefix": "duedate_1m_5_amount",
                "dpd_field": "dpd_days_mob1",
                "overdue_threshold": 5,
                "numerator_field": "estimate_principal_remaining_mob1",
                "denominator_field": "principal",
            },
        ],
    },
    "mean_metrics": [
        {"source_field": "PTI", "output_field": "avg_PTI"},
        {"source_field": "requested_loan_amount", "output_field": "avg_requested_loan_amount"},
        {"source_field": "deal_total_amount", "output_field": "avg_total_amount"},
        {"source_field": "gross_surplus", "output_field": "avg_gross_surplus"},
        {"source_field": "net_surplus", "output_field": "avg_net_surplus"},
        {"source_field": "total_income", "output_field": "avg_total_income"},
    ],
    "user_profile_metrics": {
        "numeric_cross_metrics": [
            {"category": "basic_profile", "source_field": "age", "output_field": "avg_age", "agg": "mean"},
            {"category": "basic_profile", "source_field": "dependents", "output_field": "avg_dependents", "agg": "mean"},
            {
                "category": "occupation_profile",
                "source_field": "bank_txn_industry_primary_industry_amt",
                "output_field": "avg_bank_txn_industry_primary_industry_amt",
                "agg": "mean",
            },
            {
                "category": "occupation_profile",
                "source_field": "bank_txn_industry_pay_interval_median",
                "output_field": "avg_bank_txn_industry_pay_interval_median",
                "agg": "mean",
            },
            {
                "category": "occupation_profile",
                "source_field": "bank_txn_industry_pay_interval_std",
                "output_field": "avg_bank_txn_industry_pay_interval_std",
                "agg": "mean",
            },
            {
                "category": "occupation_profile",
                "source_field": "bank_txn_industry_primary_employer_ratio",
                "output_field": "avg_bank_txn_industry_primary_employer_ratio",
                "agg": "mean",
            },
            {
                "category": "occupation_profile",
                "source_field": "bank_txn_industry_employer_cnt",
                "output_field": "avg_bank_txn_industry_employer_cnt",
                "agg": "mean",
            },
        ],
        "category_distribution_metrics": [
            {"sheet": "geo_profile_distribution", "source_field": "state", "top_n": 20, "missing_label": "Missing", "others_label": "Others"},
            {"sheet": "geo_profile_distribution", "source_field": "suburb", "top_n": 20, "missing_label": "Missing", "others_label": "Others"},
            {"sheet": "family_profile_distribution", "source_field": "family_type", "top_n": 20, "missing_label": "Missing", "others_label": "Others"},
            {
                "sheet": "attributed_category_distribution",
                "source_field": "attributed_category",
                "top_n": 20,
                "missing_label": "Missing",
                "others_label": "Others",
            },
            {
                "sheet": "occupation_profile_distribution",
                "source_field": "bank_txn_industry_primary_industry",
                "top_n": 20,
                "missing_label": "Missing",
                "others_label": "Others",
            },
            {
                "sheet": "occupation_profile_distribution",
                "source_field": "bank_txn_industry_primary_employer",
                "top_n": 20,
                "missing_label": "Missing",
                "others_label": "Others",
            },
        ],
    },
    "conversion": {
        "application_status_field": "application_status",
        "assessment_status_field": "assessment_status",
        "deal_status_field": "status",
        "incomplete_status_values": ["0.Incomplete", "1.In Progress"],
        "approved_status_prefixes": ["3", "4"],
        "auto_approved_keyword": "Auto Approved",
        "manual_approved_keyword": "Manual Approved",
        "deal_status_values": ["Active_Account", "Closed", "Blocked"],
        "output_fields": {
            "completed_flag": "is_completed_application",
            "approved_flag": "is_approved_application",
            "auto_approved_flag": "is_auto_approved_application",
            "manual_approved_flag": "is_manual_approved_application",
            "deal_flag": "is_deal_application",
            "conversion_stage": "conversion_stage",
        },
    },
}
