CONFIG = {
    "project": {
        "root_dir": ".",
        "output_dir": "./output/model_analysis_20260429",
        "encoding": "utf-8-sig",
    },
    "runtime": {
        "log_level": "INFO",
        "fail_on_missing_required_columns": False,
        "overwrite_output": True,
        "pandas_read_csv_kwargs": {
            "low_memory": False,
        },
    },
    "input_tables": {
        "base_sample": {
            "path": "./INPUT/main_analysis_model.csv",
            "description": "base sample with primary model score",
        },
        "customer_profile": {
            "path": "./INPUT/business_analysis_variable_library.csv",
            "description": "business analysis variable library",
        },
        "comparison_score": {
            "path": "./INPUT/cross_model_score.csv",
            "description": "comparison model score",
        },
        "feature_detail": {
            "path": "./INPUT/model_variable_library.csv",
            "description": "model variable library",
        },
        "txn_industry_features": {
            "path": "./INPUT/occupation_information.csv",
            "description": "occupation information",
            "optional": True,
        },
    },
    "keys": {
        "primary_key": "application_id",
        "user_key": "user_id",
        "datetime_key": "sample_datetime",
        "datetime_aliases": ["sample_datetime", "sample_datime"],
    },
    "score_binning": {
        "unknown_label": None,
        "null_label": None,
        "binning_mode": "upper_bound",
        "output_bin_count": 5,
        "scores": [
            {
                "name": "primary_model_score",
                "source_table": "base_sample",
                "score_field": "aus_new_worthiness_bid_3rdmodel_v1_0_20260429",
                "bin_field": "primary_model_score_bin",
                "bin_label_type": "int",
                "null_label": None,
                "null_values": [-1],
                "else_label": 100,
"bins": [
    {"label": 10, "min_score": 0.050829, "max_score": 0.134913},
    {"label": 20, "min_score": 0.134927, "max_score": 0.166178},
    {"label": 30, "min_score": 0.166214, "max_score": 0.193127},
    {"label": 40, "min_score": 0.193129, "max_score": 0.221320},
    {"label": 50, "min_score": 0.221326, "max_score": 0.250147},
    {"label": 60, "min_score": 0.250221, "max_score": 0.281253},
    {"label": 70, "min_score": 0.281266, "max_score": 0.318016},
    {"label": 80, "min_score": 0.318031, "max_score": 0.364808},
    {"label": 90, "min_score": 0.364830, "max_score": 0.432379},
    {"label": 100, "min_score": 0.432389, "max_score": 0.705449}
]
            },
            {
                "name": "comparison_model_score",
                "source_table": "comparison_score",
                "score_field": "aus_new_risk_bid_3rdmodel_v1_0_20251201",
                "bin_field": "comparison_model_score_bin",
                "bin_label_type": "int",
                "null_label": None,
                "null_values": [-1],
                "else_label": 100,
                "bins": [
                    {"label": 10, "min_score": 0.020419, "max_score": 0.048577},
                    {"label": 20, "min_score": 0.048631, "max_score": 0.062086},
                    {"label": 30, "min_score": 0.062116, "max_score": 0.075629},
                    {"label": 40, "min_score": 0.075668, "max_score": 0.091284},
                    {"label": 50, "min_score": 0.091289, "max_score": 0.109224},
                    {"label": 60, "min_score": 0.109264, "max_score": 0.128392},
                    {"label": 70, "min_score": 0.128397, "max_score": 0.154584},
                    {"label": 80, "min_score": 0.154598, "max_score": 0.188973},
                    {"label": 90, "min_score": 0.189020, "max_score": 0.240037},
                    {"label": 100, "min_score": 0.240060, "max_score": 0.615365},
                ],
            },
        ],
    },
    "joins": {
        "customer_profile": {
            "enabled": True,
            "source_table": "customer_profile",
            "join_key": "application_id",
            "how": "left",
            "deduplicate_key": True,
            "fields": [
                "last_step",
                "loan_tag",
                "age",
                "base_probability",
                "PTI",
                "principal",
                "estimate_principal_remaining_mob3",
                "dpd_days_mob3",
                "estimate_principal_remaining_mob1",
                "dpd_days_mob1",
                "gross_surplus",
                "net_surplus",
                "total_income",
                "requested_loan_amount",
                "requested_loan_tag",
                "state",
                "suburb",
                "family_type",
                "dependents",
                "attributed_category",
                "total_amount",
                "duedate_1m_5",
                "duedate_3m_30",
                "application_status",
                "assessment_status",
                "status",
            ],
        },
        "comparison_score": {
            "enabled": True,
            "source_table": "comparison_score",
            "join_key": "application_id",
            "how": "left",
            "deduplicate_key": True,
            "fields": [
                "aus_new_risk_bid_3rdmodel_v1_0_20251201",
            ],
        },
        "feature_detail": {
            "enabled": True,
            "source_table": "feature_detail",
            "join_key": "application_id",
            "how": "left",
            "deduplicate_key": True,
        },
        "txn_industry_features": {
            "enabled": True,
            "source_table": "txn_industry_features",
            "join_key": "application_id",
            "how": "left",
            "deduplicate_key": True,
            "fields": [
                "bank_txn_industry_primary_industry",
                "bank_txn_industry_primary_industry_amt",
                "bank_txn_industry_pay_interval_median",
                "bank_txn_industry_pay_interval_std",
                "bank_txn_industry_primary_employer",
                "bank_txn_industry_primary_employer_ratio",
                "bank_txn_industry_employer_cnt",
            ],
        },
    },
    "amount_rules": {
        "deal_status_field": "status",
        "deal_status_values": ["Active_Account", "Closed", "Blocked"],
        "total_amount_field": "total_amount",
        "deal_total_amount_field": "deal_total_amount",
    },
    "risk_metrics": {
        "label_metrics": [
            {
                "field": "duedate_3m_30",
                "prefix": "duedate_3m_30",
                "bad_values": [1],
                "good_values": [0],
            },
            {
                "field": "duedate_1m_5",
                "prefix": "duedate_1m_5",
                "bad_values": [1],
                "good_values": [0],
            },
        ],
        "amount_overdue_metrics": [
            {
                "name": "duedate_3m_30_amount_overdue_rate",
                "prefix": "duedate_3m_30_amount",
                "dpd_field": "dpd_days_mob3",
                "overdue_threshold": 30,
                "numerator_field": "estimate_principal_remaining_mob3",
                "denominator_field": "principal",
            },
            {
                "name": "duedate_1m_5_amount_overdue_rate",
                "prefix": "duedate_1m_5_amount",
                "dpd_field": "dpd_days_mob1",
                "overdue_threshold": 5,
                "numerator_field": "estimate_principal_remaining_mob1",
                "denominator_field": "principal",
            },
        ],
    },
    "mean_metrics": [
        {"source_field": "PTI", "output_field": "avg_PTI"},
        {"source_field": "requested_loan_amount", "output_field": "avg_requested_loan_amount"},
        {"source_field": "deal_total_amount", "output_field": "avg_total_amount"},
        {"source_field": "gross_surplus", "output_field": "avg_gross_surplus"},
        {"source_field": "net_surplus", "output_field": "avg_net_surplus"},
        {"source_field": "total_income", "output_field": "avg_total_income"},
        {
            "source_field": "bank_txn_industry_primary_industry_amt",
            "output_field": "avg_bank_txn_industry_primary_industry_amt",
        },
        {
            "source_field": "bank_txn_industry_pay_interval_median",
            "output_field": "avg_bank_txn_industry_pay_interval_median",
        },
        {
            "source_field": "bank_txn_industry_pay_interval_std",
            "output_field": "avg_bank_txn_industry_pay_interval_std",
        },
        {
            "source_field": "bank_txn_industry_primary_employer_ratio",
            "output_field": "avg_bank_txn_industry_primary_employer_ratio",
        },
        {
            "source_field": "bank_txn_industry_employer_cnt",
            "output_field": "avg_bank_txn_industry_employer_cnt",
        },
    ],
    "conversion": {
        "enabled": True,
        "application_status_field": "application_status",
        "assessment_status_field": "assessment_status",
        "deal_status_field": "status",
        "incomplete_status_values": ["0.Incomplete", "1.In Progress"],
        "approved_status_prefixes": ["3", "4"],
        "auto_approved_keyword": "Auto Approved",
        "manual_approved_keyword": "Manual Approved",
        "deal_status_values": ["Active_Account", "Closed", "Blocked"],
        "output_fields": {
            "completed_flag": "is_completed_application",
            "approved_flag": "is_approved_application",
            "auto_approved_flag": "is_auto_approved_application",
            "manual_approved_flag": "is_manual_approved_application",
            "deal_flag": "is_deal_application",
            "conversion_stage": "conversion_stage",
        },
    },
    "analysis": {
        "base_table": "base_sample",
        "sample_month_field": "sample_month",
        "monthly_group_analyses": {
            "enabled": True,
            "output_suffix": "_by_sample_month",
        },
        "enabled_outputs": {
            "data_quality_summary": True,
            "enriched_base_sample": True,
            "primary_model_bin_performance": True,
            "conversion_by_primary_model_bin": True,
            "primary_model_bin_x_conversion_stage": True,
            "primary_vs_comparison_model_bin": True,
            "feature_profile_by_group": True,
            "feature_profile_by_category": True,
        },
        "group_analyses": [
            {
                "name": "primary_model_bin_performance",
                "group_by": ["primary_model_score_bin"],
                "output_file": "02_primary_model_bin_performance.csv",
                "include_all_metrics": True,
            },
            {
                "name": "conversion_by_primary_model_bin",
                "group_by": ["primary_model_score_bin"],
                "output_file": "03_conversion_by_primary_model_bin.csv",
                "include_metric_groups": ["sample", "conversion"],
            },
            {
                "name": "primary_model_bin_x_conversion_stage",
                "group_by": ["primary_model_score_bin", "conversion_stage"],
                "output_file": "04_primary_model_bin_x_conversion_stage.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_vs_comparison_model_bin",
                "group_by": ["primary_model_score_bin", "comparison_model_score_bin"],
                "output_file": "05_primary_vs_comparison_model_bin.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_last_step",
                "group_by": ["primary_model_score_bin", "last_step"],
                "output_file": "08_primary_model_bin_x_last_step.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_loan_tag",
                "group_by": ["primary_model_score_bin", "loan_tag"],
                "output_file": "09_primary_model_bin_x_loan_tag.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_requested_loan_tag",
                "group_by": ["primary_model_score_bin", "requested_loan_tag"],
                "output_file": "10_primary_model_bin_x_requested_loan_tag.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_state",
                "group_by": ["primary_model_score_bin", "state"],
                "output_file": "11_primary_model_bin_x_state.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_suburb",
                "group_by": ["primary_model_score_bin", "suburb"],
                "output_file": "12_primary_model_bin_x_suburb.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_family_type",
                "group_by": ["primary_model_score_bin", "family_type"],
                "output_file": "13_primary_model_bin_x_family_type.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_attributed_category",
                "group_by": ["primary_model_score_bin", "attributed_category"],
                "output_file": "14_primary_model_bin_x_attributed_category.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_age",
                "group_by": ["primary_model_score_bin", "age"],
                "merged_output_file": "15_primary_model_bin_x_discrete_numeric.csv",
                "merge_group_label": "age",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_dependents",
                "group_by": ["primary_model_score_bin", "dependents"],
                "merged_output_file": "15_primary_model_bin_x_discrete_numeric.csv",
                "merge_group_label": "dependents",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_primary_industry",
                "group_by": ["primary_model_score_bin", "bank_txn_industry_primary_industry"],
                "output_file": "17_primary_model_bin_x_primary_industry.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_primary_employer",
                "group_by": ["primary_model_score_bin", "bank_txn_industry_primary_employer"],
                "output_file": "18_primary_model_bin_x_primary_employer.csv",
                "include_all_metrics": True,
            },
            {
                "name": "primary_model_bin_x_employer_cnt",
                "group_by": ["primary_model_score_bin", "bank_txn_industry_employer_cnt"],
                "merged_output_file": "15_primary_model_bin_x_discrete_numeric.csv",
                "merge_group_label": "bank_txn_industry_employer_cnt",
                "include_all_metrics": True,
            },
        ],
        "monthly_analyses": [
            {
                "name": "primary_model_bin_x_sample_month_apply_cnt",
                "group_by": ["primary_model_score_bin"],
                "metric_field": "apply_cnt",
                "output_file": "20_primary_model_bin_x_sample_month_apply_cnt.csv",
                "include_metric_groups": ["sample", "conversion"],
            },
            {
                "name": "primary_model_bin_x_sample_month_duedate_1m_5_bad_rate",
                "group_by": ["primary_model_score_bin"],
                "metric_field": "duedate_1m_5_bad_rate",
                "output_file": "21_primary_model_bin_x_sample_month_duedate_1m_5_bad_rate.csv",
                "value_format": "percent_1",
            },
            {
                "name": "primary_model_bin_x_sample_month_duedate_3m_30_bad_rate",
                "group_by": ["primary_model_score_bin"],
                "metric_field": "duedate_3m_30_bad_rate",
                "output_file": "22_primary_model_bin_x_sample_month_duedate_3m_30_bad_rate.csv",
                "value_format": "percent_1",
            },
            {
                "name": "primary_model_bin_x_sample_month_duedate_1m_5_amount_overdue_rate",
                "group_by": ["primary_model_score_bin"],
                "metric_field": "duedate_1m_5_amount_overdue_rate",
                "output_file": "23_primary_model_bin_x_sample_month_duedate_1m_5_amount_overdue_rate.csv",
                "value_format": "percent_1",
            },
            {
                "name": "primary_model_bin_x_sample_month_duedate_3m_30_amount_overdue_rate",
                "group_by": ["primary_model_score_bin"],
                "metric_field": "duedate_3m_30_amount_overdue_rate",
                "output_file": "24_primary_model_bin_x_sample_month_duedate_3m_30_amount_overdue_rate.csv",
                "value_format": "percent_1",
            },
        ],
    },
    "feature_profile": {
        "enabled": True,
        "source_table": "feature_detail",
        "join_key": "application_id",
        "group_by": ["primary_model_score_bin"],
        "percentiles": [0.25, 0.5, 0.75, 0.9],
        "output_file_by_bin": "06_feature_profile_by_primary_group.csv",
        "output_file_by_category": "07_feature_profile_by_category.csv",
        "output_split_by_category_dir": "feature_profile_by_category",
        "categories": {
            "txn_income": {
                "description": "income stability",
                "fields": [
                    "bank_txn_income_global_sum_168d",
                    "bank_txn_income_global_count_168d",
                    "bank_txn_income_global_mean_168d",
                    "bank_txn_income_global_median_168d",
                    "bank_txn_income_global_std_168d",
                    "bank_txn_income_global_cv_168d",
                    "bank_txn_income_wages_sum_168d",
                    "bank_txn_income_wages_count_168d",
                    "bank_txn_income_wages_mean_168d",
                    "bank_txn_income_wages_cv_168d",
                    "bank_txn_income_wages_ratio_168d",
                    "bank_txn_income_wages_trend_slope_168d",
                    "bank_txn_income_wages_interval_std",
                    "bank_txn_income_wages_interval_max",
                    "bank_txn_income_wages_interval_gap_30_count",
                    "bank_txn_income_centrelink_sum_168d",
                    "bank_txn_income_centrelink_ratio_168d",
                    "bank_txn_income_otherincome_sum_168d",
                    "bank_txn_income_otherincome_ratio_168d",
                    "bank_txn_income_wages_mean_consumption_rate_168d",
                ],
            },
            "txn_expense": {
                "description": "expense structure",
                "fields": [
                    "bank_txn_expense_global_sum_168d",
                    "bank_txn_expense_global_count_168d",
                    "bank_txn_expense_global_mean_168d",
                    "bank_txn_expense_global_median_168d",
                    "bank_txn_expense_global_std_168d",
                    "bank_txn_expense_global_cv_168d",
                    "bank_txn_expense_rent_sum_168d",
                    "bank_txn_expense_groceries_sum_168d",
                    "bank_txn_expense_diningout_sum_168d",
                    "bank_txn_expense_retail_sum_168d",
                    "bank_txn_expense_utilities_sum_168d",
                    "bank_txn_expense_telecommunications_sum_168d",
                    "bank_txn_expense_fees_sum_168d",
                    "bank_txn_expense_gambling_sum_168d",
                    "bank_txn_expense_externaltransfers_sum_168d",
                    "bank_txn_expense_rent_trend_slope_168d",
                    "bank_txn_expense_groceries_trend_slope_168d",
                    "bank_txn_expense_gambling_trend_slope_168d",
                ],
            },
            "txn_eod": {
                "description": "balance stability",
                "fields": [
                    "bank_txn_balance_mean_168d",
                    "bank_txn_balance_min_168d",
                    "bank_txn_balance_max_168d",
                    "bank_txn_balance_std_168d",
                    "bank_txn_balance_snapshot_last_168d",
                    "bank_txn_balance_anomaly_days_168d",
                    "bank_txn_balance_fluctuation_anomaly_days_168d",
                    "bank_txn_balance_streak_dec_max_168d",
                    "bank_txn_balance_streak_inc_max_168d",
                    "bank_txn_balance_global_balance_to_debit_ratio_mean_168d",
                    "bank_txn_balance_pct_change_mean_168d",
                    "bank_txn_balance_sign_change_count_168d",
                    "bank_txn_balance_debit_tail_ratio_168d",
                    "bank_txn_balance_credit_tail_ratio_168d",
                ],
            },
            "txn_surplus": {
                "description": "cashflow surplus",
                "fields": [
                    "bank_txn_surplus_income_sum_168d",
                    "bank_txn_surplus_expense_sum_168d",
                    "bank_txn_surplus_liabilityrepayment_sum_168d",
                    "bank_txn_surplus_liabilitydrawdown_sum_168d",
                    "bank_txn_surplus_fortnightly_income_168d",
                    "bank_txn_surplus_fortnightly_expense_168d",
                    "bank_txn_surplus_fortnightly_liabilityrepayment_168d",
                    "bank_txn_surplus_fortnightly_liabilitydrawdown_168d",
                    "bank_txn_surplus_fortnightly_surplus_168d",
                    "bank_txn_surplus_income_1m_vs_6m",
                    "bank_txn_surplus_expense_1m_vs_6m",
                    "bank_txn_surplus_liabilityrepayment_1m_vs_6m",
                    "bank_txn_surplus_liabilitydrawdown_1m_vs_6m",
                    "bank_txn_surplus_surplus_1m_vs_6m",
                ],
            },
            "txn_cate": {
                "description": "transaction preference",
                "fields": [
                    "bank_txn_category_global_amt_168d",
                    "bank_txn_category_global_cnt_168d",
                    "bank_txn_category_global_credit_amt_168d",
                    "bank_txn_category_global_debit_amt_168d",
                    "bank_txn_category_global_burn_rate_168d",
                    "bank_txn_category_global_saving_rate_168d",
                    "bank_txn_category_global_income_share_168d",
                    "bank_txn_category_global_debit_share_168d",
                    "bank_txn_category_active_days_168d",
                    "bank_txn_category_inter_txn_gap_p50_168d",
                    "bank_txn_category_inter_txn_gap_p90_168d",
                    "bank_txn_category_neg_net_streak_days_168d",
                    "bank_txn_category_rent_after_wage_lag_p50_168d",
                    "bank_txn_category_rent_share_168d",
                    "bank_txn_category_groceries_share_168d",
                    "bank_txn_category_dining_out_share_168d",
                    "bank_txn_category_gambling_share_168d",
                    "bank_txn_category_sacc_loans_share_168d",
                    "bank_txn_category_non_sacc_loans_share_168d",
                    "bank_txn_category_credit_card_repayments_share_168d",
                    "bank_txn_category_dishonours_share_168d",
                    "bank_txn_category_overdrawn_share_168d",
                ],
            },
            "txn_lender": {
                "description": "lender behavior",
                "fields": [
                    "bank_txn_lender_repay_amount_sum",
                    "bank_txn_lender_repay_count",
                    "bank_txn_lender_disburse_amount_sum",
                    "bank_txn_lender_disburse_count",
                    "bank_txn_lender_repay_advance_amount_sum",
                    "bank_txn_lender_repay_advance_count",
                    "bank_txn_lender_disburse_advance_amount_sum",
                    "bank_txn_lender_disburse_advance_count",
                    "bank_txn_lender_repay_bnpl_amount_sum",
                    "bank_txn_lender_repay_bnpl_count",
                    "bank_txn_lender_disburse_bnpl_amount_sum",
                    "bank_txn_lender_disburse_bnpl_count",
                    "bank_txn_lender_repay_loan_amount_sum",
                    "bank_txn_lender_repay_loan_count",
                    "bank_txn_lender_disburse_loan_amount_sum",
                    "bank_txn_lender_disburse_loan_count",
                    "bank_txn_lender_repay_single_amount_max",
                    "bank_txn_lender_disburse_single_amount_max",
                ],
            },
        },
    },
    "pivot_export": {
        "enabled": True,
        "input_file": "05_primary_vs_comparison_model_bin.csv",
        "output_excel": "model_compare_pivot.xlsx",
        "row_dim": "primary_model_score_bin",
        "col_dim": "comparison_model_score_bin",
        "metrics": [
            "sample_cnt",
            "sample_pct",
            "duedate_3m_30_valid_cnt",
            "duedate_3m_30_bad_cnt",
            "duedate_3m_30_good_cnt",
            "duedate_3m_30_bad_rate",
            "duedate_1m_5_valid_cnt",
            "duedate_1m_5_bad_cnt",
            "duedate_1m_5_good_cnt",
            "duedate_1m_5_bad_rate",
            "duedate_3m_30_amount_overdue_amount",
            "duedate_3m_30_amount_principal_amount",
            "duedate_3m_30_amount_overdue_rate",
            "duedate_1m_5_amount_overdue_amount",
            "duedate_1m_5_amount_principal_amount",
            "duedate_1m_5_amount_overdue_rate",
            "avg_PTI",
            "avg_requested_loan_amount",
            "avg_total_amount",
            "avg_gross_surplus",
            "avg_net_surplus",
            "avg_total_income",
            "avg_bank_txn_industry_primary_industry_amt",
            "avg_bank_txn_industry_pay_interval_median",
            "avg_bank_txn_industry_pay_interval_std",
            "avg_bank_txn_industry_primary_employer_ratio",
            "avg_bank_txn_industry_employer_cnt",
            "apply_cnt",
            "completed_application_cnt",
            "approved_application_cnt",
            "auto_approved_application_cnt",
            "manual_approved_application_cnt",
            "deal_sample_cnt",
            "completion_rate",
            "approval_rate",
            "auto_approval_rate",
            "manual_approval_rate",
            "auto_approval_share",
            "manual_approval_share",
            "deal_rate",
        ],
    },
    "outputs": {
        "data_quality_summary": "00_data_quality_summary.csv",
        "enriched_base_sample": "01_enriched_base_sample.csv",
        "excel_workbook": "model_analysis_outputs.xlsx",
        "run_log": "run_log.txt",
    },
}
